const englishWordsList = [
  ['whim', 'прихоть'],
  ['i consider that the', 'я считаю, что'],
  ['expressed', 'выразил'],
  ['goofball', 'тупица'],
  ['malice', 'злоба'],
  ['Perhaps', 'Возможно'],
  ['inquiring', 'спрашивая'],
  ['pursuit', 'преследование'],
  ['Immense', 'Огромный / Необъятный'],
  ['Purpose', 'Цель'],
  ['concerned', 'обеспокоенный'],
  [`this isn't an issue of whether`, 'вопрос не в том, ...'],
  ['its futile', 'это бесполезно'],
  [`i've met my quota`, 'я выполнил свою квоту'],
  ['am not aware of', 'не знаю / я не в курсе'],
  ['render', 'оказывать'],
  ['unpredictable', 'непредсказуемый'],
  ['handy', 'удобный'],
  ['enormous', 'громадный'],
  ['pass sth off as sth', 'выдать что-то за что-то'],
  ['unconscious', 'без сознания'],
  ['approximately', 'примерно'],
  ['sentence', 'приговор'],
  ['neat', 'аккуратный'],
  ['it’s very janky', 'это очень неприятно'],
  ['explicit', 'явный'],
  ['beats me', 'не знаю'],
  ['neat', 'аккуратный'],
  ['neat', 'аккуратный'],
  ['neat', 'аккуратный'],
  ['neat', 'аккуратный'],
  ['neat', 'аккуратный'],
];
