const englishWordsList = [];

englishWordsList.push(['whim', 'прихоть']);
englishWordsList.push(['i consider that the', 'я считаю, что']);
englishWordsList.push(['expressed', 'выразил']);
englishWordsList.push(['goofball', 'тупица']);
englishWordsList.push(['malice', 'злоба']);
englishWordsList.push(['Perhaps', 'Возможно']);
englishWordsList.push(['inquiring', 'спрашивая']);
englishWordsList.push(['pursuit', 'преследование']);
englishWordsList.push(['Immense', 'Огромный / Необъятный']);
englishWordsList.push(['Purpose', 'Цель']);
englishWordsList.push(['concerned', 'обеспокоенный']);
englishWordsList.push([`this isn't an issue of whether`, 'вопрос не в том, ...']);
englishWordsList.push(['its futile', 'это бесполезно']);
englishWordsList.push([`i've met my quota`, 'я выполнил свою квоту']);
englishWordsList.push(['am not aware of', 'не знаю / я не в курсе']);
englishWordsList.push(['render', 'оказывать']);
englishWordsList.push(['unpredictable', 'непредсказуемый']);
englishWordsList.push(['handy', 'удобный']);
englishWordsList.push(['enormous', 'громадный']);
englishWordsList.push(['pass sth off as sth', 'выдать что-то за что-то']);
englishWordsList.push(['unconscious', 'без сознания']);
englishWordsList.push(['approximately', 'примерно']);
englishWordsList.push(['sentence', 'приговор']);
englishWordsList.push(['neat', 'аккуратный']);
englishWordsList.push(['it’s very janky', 'это очень неприятно']);
englishWordsList.push(['explicit', 'явный']);
englishWordsList.push(['beats me', 'не знаю']);
englishWordsList.push(['neat', 'аккуратный']);
englishWordsList.push(['neat', 'аккуратный']);
englishWordsList.push(['neat', 'аккуратный']);
englishWordsList.push(['neat', 'аккуратный']);
englishWordsList.push(['neat', 'аккуратный']);

export { englishWordsList };
